name: Mercedes Luis Fuentes
favicon: null
layout_spectrum: 0.24547
typography_spectrum: 0.9513032685499638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030502'
    - '#cfcec9'
    - '#476173'
    - '#969694'
    - '#c06670'
  brandStrength: 0.25
  lightness: 0.2835137185174972
  saturation: 0.6681278832256794
  rhythmicContrast: 0.30571350967511535
purpose: []
